language: objective-c
osx_image: xcode9.4
xcode_workspace: SmartReceipts.xcworkspace
xcode_scheme: SmartReceipts
notifications:
  email:
    recipients:
      - support@smartreceipts.co
    on_success: never # default: change
    on_failure: always # default: always
before_install:
- openssl aes-256-cbc -K $encrypted_8f779a1b4fcd_key -iv $encrypted_8f779a1b4fcd_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
script:
- xcodebuild clean build test -quiet -sdk iphonesimulator -workspace SmartReceipts.xcworkspace -scheme SmartReceipts CODE_SIGNING_REQUIRED=NO
