language: objective-c
osx_image: xcode9.4
xcode_workspace: SmartReceipts.xcworkspace
xcode_scheme: SmartReceipts
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace SmartReceipts.xcworkspace -scheme SmartReceipts CODE_SIGNING_REQUIRED=NO | xcpretty -c
